chatGPTAccountPool:
  - email: "x5mgvb41j@mail.yitun.net"
    password: "HyVmv30l"
    isGoogleLogin: false
chatPrivateTiggerKeyword: ""
openAIProxy: "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"
